YuGiOhOnline1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('socketio_app.urls')),
    path('admin/', admin.site.urls),
]

"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('socketio_app.urls')),
    url(r'^admin/', admin.site.urls),
]
"""

socketio_app/urls.py
from django.urls import path

from . import views

app_name="socketio_app"
urlpatterns = [
    path('', views.index, name='index'),
    path('new_duel/', views.create_new_duel, name='new_duel'),
    path('lobby/<int:duel_url>/', views.duel_lobby, name='duel_lobby'),
    path('enter_duel/<int:duel_url>/', views.enter_duel_room, name='enter_duel_room'),
    path('duel/<int:duel_url>/', views.duel_room, name='duel_room'),
]

socketio_app/models.py
from django.db import models


# Create your models here.

class Duel(models.Model):

    duel_url = models.IntegerField(default=0)
    #can_begin = models.BooleanField(default=False)
    player_zero_joined = models.BooleanField(default=False)
    player_one_joined = models.BooleanField(default=False)

class Player(models.Model):

    duel = models.ForeignKey(Duel, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=25)
    player_number = models.IntegerField(default=0)
    sid = models.CharField(max_length=100, default="dpc")

class Spectator(models.Model):

    duel = models.ForeignKey(Duel, on_delete=models.CASCADE)
    

socketio_app/views.py
# set async_mode to 'threading', 'eventlet', 'gevent' or 'gevent_uwsgi' to
# force a mode else, the best mode is selected automatically from what's
# installed
async_mode = None

import os

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
import socketio

from socketio_app.models import Duel, Player
import engine.GameState
import engine.Player


sio = socketio.Server(async_mode=async_mode)
thread = None


gameStates = {}  #TODO : put this into a managing class
gameStatesBySid = {}

def index(request):
    #global thread
    #if thread is None:
    #    thread = sio.start_background_task(background_thread)

    return render(request, 'socketio_app/index.html', {})
    
def create_new_duel(request):
    #create new duel and get its ID
    
    newduel = Duel.objects.create()
    print("new duel id ", newduel.id)
    newduel.duel_url = newduel.id
    newduel.save()
    
    gameStates[newduel.id] = engine.GameState.get_default_gamestate(sio, newduel.id)

    return HttpResponseRedirect(reverse('socketio_app:duel_lobby', args=(newduel.duel_url,)))

def duel_lobby(request, duel_url):
    duel = get_object_or_404(Duel, pk=duel_url)
    if (duel.player_set.count() >= 2):
        print("duel with 2 or more players")
        return HttpResponseRedirect(reverse('socketio_app:duel_room', args=(duel.id,)) + "?player_id=SPECTATOR")
    else:
        print("duel with less than two players")
        return render(request, 'socketio_app/duel_lobby.html', {'duel': duel})

def enter_duel_room(request, duel_url): #for entering the duel room as a player
    duel = get_object_or_404(Duel, pk=duel_url)
    nickname = request.POST['nickname']
    #check if nickname doesn't exist, if so
    if (duel.player_set.count() < 2):
        pnum =  duel.player_set.count()
        duel.player_set.create(nickname = nickname, player_number = pnum)
        theplayer = duel.player_set.last()
        return HttpResponseRedirect(reverse('socketio_app:duel_room', args=(duel.id,)) + "?player_id=" + str(theplayer.id))
    else:
        return render(request, 'socketio_app/duel_lobby.html', {'duel': duel, 'error_message':"The duel already has two players"})
    
def duel_room(request, duel_url):
    duel = get_object_or_404(Duel, pk=duel_url)
    player_id = request.GET.get('player_id')
    
    player_number = ""
    player_nickname = ""

    if player_id == "None" or player_id == "SPECTATOR":
        player_number = "SPECTATOR"
        player_nickname = "Spectator"
    else:
        player = get_object_or_404(Player, pk=int(player_id))
        player_number = player.player_number
        player_nickname = player.nickname

    return render(request, 'socketio_app/duel_room.html', {'duel' : duel, 'player_number': player_number, 'player_nickname' : player_nickname})


def background_thread():
    #Example of how to send server generated events to clients.
    count = 0
    while True:
        sio.sleep(10)
        count += 1
        sio.emit('my_response', {'data': 'Server generated event'},
                 namespace='/test')

def startup_GameState(duel_id):
    gameStates[duel_id].startup()
    
@sio.event
def join_duel_room(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    sio.enter_room(sid, "duel" + str(duel.id) + "_public_info")
    gameStatesBySid[sid] = gameStates[duel.id]

    if (message['pnum'] == "0" and duel.player_zero_joined == False):
        playerzero = duel.player_set.get(player_number = 0)
        playerzero.sid = sid
        playerzero.save()
        duel.player_zero_joined = True
        duel.save()
        print("Player 0 joined")
        sio.enter_room(sid, "duel" + str(duel.id) + "_player0_info")
        gameStates[duel.id].dict_of_sids[0] = sid
 
    elif (message['pnum'] == "1" and duel.player_one_joined == False):
        playerone = duel.player_set.get(player_number = 1)
        playerone.sid = sid
        playerone.save()
        duel.player_one_joined = True
        duel.save()
        print("Player 1 joined")
        sio.enter_room(sid, "duel" + str(duel.id) + "_player1_info")
        gameStates[duel.id].dict_of_sids[1] = sid
    
    elif (message['pnum'] == "SPECTATOR"):
        print("Spectator joined")
        spectator_id = gameStates[duel.id].spectator_count
        sio.enter_room(sid, "duel" + str(duel.id) + "_spectator_info")
        sio.enter_room(sid, "duel" + str(duel.id) + "_spectator" + str(spectator_id) + "_info")
        gameStates[duel.id].dict_of_sids['spectator' + str(spectator_id)] = sid
        gameStates[duel.id].spectator_count += 1

        if len(gameStates[duel.id].waiting_for_players) > 0:
            gameStates[duel.id].spectators_to_refresh_view.append(spectator_id)
        else:
            gameStates[duel.id].refresh_view(spectator_id)

        
    
    if duel.player_one_joined == True and duel.player_zero_joined == True and gameStates.get(duel.id) is not None:
        if gameStates.get(duel.id).has_started == False:
            print(duel.id, "beginning")
            startup_GameState(duel.id)


@sio.event
def ask_for_action_choices(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))

    if (message['pnum'] != 'SPECTATOR'):
        theplayer = duel.player_set.get(player_number = int(message['pnum']))
        if (theplayer.sid == sid):
            print("ask for action choices on card", message['cardid'])
            
            action_name_list = gameStates[duel.id].return_available_action_names(int(message['cardid']))
        
            print(action_name_list)
            sio.emit('display_action_choices', {'cardid': message['cardid'], 'actions': action_name_list}, room=sid)
        else:
            print("Fake player attempted to create action list")

@sio.event
def button_activated(sid, message):
    print("Button unclicked event for player", message['pnum']) 

@sio.event
def ask_run_action(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    theplayer = duel.player_set.get(player_number = int(message['pnum']))
    
    if (theplayer.sid == sid): #ask_for_action_choices already asked for that
       gameStates[duel.id].run_action_asked_for(int(message['cardid']), message['action_name'])


@sio.event
def move_complete(sid, message): #this should actually be called animation_complete
   
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    #theplayer = duel.player_set.get(player_number = int(message['pnum']))
    already_removed = False
    try:
        gameStates[duel.id].waiting_for_players.remove(sid)
    except KeyError:
        already_removed = True
        
    #the already_removed condition check is an attempt to thwart an 'unsolicited response' bug
    if already_removed == False and len(gameStates[duel.id].waiting_for_players) == 0:
        gameStates[duel.id].stop_waiting_for_players()
        

@sio.event
def target_card_chosen(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    theplayer = duel.player_set.get(player_number = int(message['pnum']))

    if (theplayer.sid == sid):
        gameStates[duel.id].process_card_choice(int(message['cardid']))

@sio.event
def target_zone_chosen(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    theplayer = duel.player_set.get(player_number = int(message['pnum']))

    if (theplayer.sid == sid):
        gameStates[duel.id].process_zone_choice(message['zonename'])

@sio.event
def send_answer(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    theplayer = duel.player_set.get(player_number = int(message['pnum']))

    if (theplayer.sid == sid):
        print(message['question'] + message['answer'])
        gameStates[duel.id].process_answer(message['question'], message['answer'])

@sio.event
def ask_phase_change(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    theplayer = duel.player_set.get(player_number = int(message['pnum']))

    if (theplayer.sid == sid):
        gameStates[duel.id].phase_transition_asked_funcs[message['phase']]()

@sio.event
def pass_action(sid, message):
    duel = get_object_or_404(Duel, pk=int(message['duelid']))
    theplayer = duel.player_set.get(player_number = int(message['pnum']))

    if (theplayer.sid == sid):
        gameStates[duel.id].keep_running_steps = True
        gameStates[duel.id].run_steps()



@sio.event
def connect(sid, environ):
    sio.emit('my_response', {'data': 'Connected', 'count': 0}, room=sid)


@sio.event
def disconnect(sid):
    print('Client disconnected')
    theGameState = gameStatesBySid[sid]
    was_waiting_for_player = True
    try:
        theGameState.waiting_for_players.remove(sid)
    except KeyError:
        was_waiting_for_player = False

    list_of_pnums_to_delete = []
    for pnum in theGameState.dict_of_sids.keys():
        if theGameState.dict_of_sids[pnum] == sid:
            list_of_pnums_to_delete.append(pnum)

    for pnum in list_of_pnums_to_delete:
        del theGameState.dict_of_sids[pnum]
    
    #Add an "end the duel if the leaving player was a duelist

    #This is there to catch the case where the last player the gamestate
    #was waiting for was a spectator and this player leaves the room before the waiting is finished.
    if was_waiting_for_player and len(theGameState.waiting_for_players) == 0:
        theGameState.stop_waiting_for_players()

socketio_app/templates/socketio_app/base.html
<!DOCTYPE HTML>
<html>
<head>

<script type="text/javascript" src="//code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.slim.js"></script>
{% block scripts %}{% endblock %}
<title>{% block title %} YuGiOh Online {% endblock %}</title>

</head>
<body>
	{% block body-classes %}{% endblock %}

</body>

</html>

socketio_app/templates/socketio_app/duel_lobby.html
{% extends 'socketio_app/base.html' %}

{% block scripts %}

{% endblock %}



{% block body-classes %}
<p> This is the duel lobby. Share this number with your friends : {{ duel.duel_url }} </p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'socketio_app:enter_duel_room' duel.duel_url %}" method="post">
	{% csrf_token %}
	<input type="text" name="nickname" id="nickname" placeholder="Nickname">
	<input type="submit" value="Join As Player">
</form>

<a href="{% url 'socketio_app:duel_room' duel.duel_url  %}?player_id=SPECTATOR"><div>Join as Spectator</div></a>

{% endblock %}

socketio_app/templates/socketio_app/duel_room.html
{% extends 'socketio_app/base.html' %}
{% block scripts %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
canvas {
    border:1px solid #d3d3d3;
    background-color: #f1f1f1;
}
</style>
<script type="text/javascript" src="{% static 'socketio_app/scripts/Utils.js' %}"></script>
<script type="text/javascript" src="{% static 'socketio_app/scripts/CardManager.js' %}"></script>
<script type="text/javascript" src="{% static 'socketio_app/scripts/Card.js' %}"></script>
<script type="text/javascript" src="{% static 'socketio_app/scripts/GameArea.js' %}"></script>
<script type="text/javascript" src="{% static 'socketio_app/scripts/CardButton.js' %}"></script>
<script type="text/javascript" src="{% static 'socketio_app/scripts/PhaseButton.js' %}"></script>
<script type="text/javascript" charset="utf-8">

function getImageFullPath(path)
{
    return "{% static 'socketio_app/images/' %}" + path;
}

function getIndexPath()
{
    return "{% url 'socketio_app:index' %}";
}


$(document).ready(function(){
	var socket = io.connect();
	
	var width = 900;
	var height = 600;

	CardManager.start(socket, '{{ player_number|escapejs }}', '{{ duel.id|escapejs }}', width, height);

	GameArea.start(width, height);
	
	CardManager.drawPhaseButtons();

	socket.on('connect', function() {
		socket.emit('join_duel_room', {pnum: '{{ player_number|escapejs }}', duelid: '{{ duel.id|escapejs }}' });
	});

	socket.on('begin_duel', function() {
		console.log("Duel began");
		$('#message').text("Duel began.");

	});

	socket.on('display_action_choices', function(msg) {
		CardManager.createCardButtons(msg.cardid, msg.actions);
	});

	socket.on('create_card', function(msg) {
		CardManager.createCard(msg.zone, false, msg.rotation, msg.imgpath, msg.player, msg.cardid);
	});
	
	socket.on('create_cards_in_hand_spectator', function(msg) {
		CardManager.createCardsInHandForSpectator(msg.player, msg.cardids, msg.imgpaths);
	});

	socket.on('move_card', function(msg) {
		CardManager.moveCard(msg.cardid, msg.zone);
	});

	socket.on('rotate_card', function(msg) {
		CardManager.rotateCard(msg.cardid, msg.rotation);
	});

	socket.on('change_card_visibility', function(msg) {
		CardManager.changeCardVisibility(msg.cardid, msg.visibility);
	});

	socket.on('erase_card', function(msg) {
		CardManager.eraseCard(msg.cardid);
	});

	socket.on('choose_card', function(msg) {
		CardManager.enterChooseTargetCardMode(msg.choices);
	});

	socket.on('choose_zone', function(msg) {
		CardManager.enterChooseZoneMode(msg.choices);
	});

	socket.on('phase_change', function(msg) {
		CardManager.PhaseFunctions[msg.phase_name]();
		
	});

	socket.on('start_waiting', function(msg) {
		CardManager.startWaiting(msg.reason);
	});

	socket.on('stop_waiting', function(msg) {
		CardManager.stopWaiting();
	});

	socket.on('ask_question', function(msg) {
		CardManager.askQuestion(msg.question, msg.choices);
	});
	socket.on('choose_next_phase', function(msg) {
		CardManager.chooseNextPhase();
	});
			       
	socket.on('multiple_action_window', function(msg) {
	    CardManager.multipleActionWindow(msg.possible_cards, msg.current_phase_or_step);
	});

	socket.on('change_LP', function(msg) {
             CardManager.changeLP(msg.player, msg.amount);
	
	});

	socket.on('end_duel', function(msg) {
             CardManager.endDuel(msg.winner);	
	});
});

</script>

{% endblock %}
{% block body-classes %}
<!-- <p> This is the duel room for duel number {{ duel.duel_url }}. </p>
<p> You are player {{ player_number }}, with nickname {{ player_nickname }}. </p> -->

<p id="message"></p>
<p id="choice_buttons"></p>


{% endblock %}

socketio_app/templates/socketio_app/index.html
<!DOCTYPE HTML>

{% extends "socketio_app/base.html" %}
{% block scripts %}
{% endblock %}
{% block body-classes %}

<li><a class="big-btn" href="{% url 'socketio_app:new_duel' %}">Create new duel</a></li>

{% endblock %}